[build]
builder = "nixpacks"
buildCommand = "npm install --production && mkdir -p dist && npx esbuild server/scraper-server.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/scraper.js"

[deploy]
startCommand = "node dist/scraper.js"

[nixpacks]
aptPkgs = [
  "wget",
  "gnupg",
  "ca-certificates",
  "fonts-liberation",
  "libappindicator3-1",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcups2",
  "libdbus-1-3",
  "libgdk-pixbuf2.0-0",
  "libnspr4",
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "xdg-utils",
  "libgbm1",
  "libpango-1.0-0",
  "libcairo2",
  "libxss1"
]
